spring.application.name=spring-security
spring.security.user.name = manoj
spring.security.user.password = 1234

server.servlet.session.cookie.same-site = strict

spring.datasource.driver-class = org.postgresql.Driver
spring.datasource.url = jdbc:postgresql://localhost:5432/quizdb
spring.datasource.username = postgres
spring.datasource.password = manojkasu

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
#spring.jpa.properties.hibernate.dialect = org.hibernate.